/*
 *                 Sun Public License Notice
 * 
 * The contents of this file are subject to the Sun Public License
 * Version 1.0 (the "License"). You may not use this file except in
 * compliance with the License. A copy of the License is available at
 * http://www.sun.com/
 * 
 * The Original Code is NetBeans. The Initial Developer of the Original
 * Code is Sun Microsystems, Inc. Portions Copyright 1997-2005 Sun
 * Microsystems, Inc. All Rights Reserved.
 */
/*
 * FinalPage.java
 *
 * Created on August 20, 2005, 2:52 PM
 */

package wizardpagedemo;

import javax.swing.table.DefaultTableModel;
import org.netbeans.spi.wizard.WizardPage;

/**
 *
 * @author  tim
 */
public class FinalPage extends WizardPage {
    public FinalPage() {
        initComponents();
    }
    
    protected void renderingPage() {
        DefaultTableModel mdl = new DefaultTableModel();
        mdl.setColumnCount(2);
        Object[] keys = getWizardDataKeys();
        mdl.setNumRows(keys.length);
        for (int i=0; i < keys.length; i++) {
            mdl.setValueAt(keys[i], i, 0);
            mdl.setValueAt(getWizardData(keys[i]), i, 1);
        }
        jTable1.setModel (mdl);
    }
    
    public static String getDescription() {
        return "Review animal specification";
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jLabel1.setText("Will create an animal with the following attributes:");
        add(jLabel1, java.awt.BorderLayout.NORTH);

    }
    // </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    
}
