/*
 * WizardInfoPanel.java
 *
 * Created on January 3, 2007, 11:50 AM
 */

package net.java.dev.wizard.template;

import java.awt.Component;
import org.netbeans.spi.wizard.WizardPage;

/**
 *
 * @author  Tim
 */
public class WizardInfoPanel extends WizardPage {
    
    /** Creates new form WizardInfoPanel */
    public WizardInfoPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        title = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();

        jLabel2.setLabelFor(title);
        jLabel2.setText(org.openide.util.NbBundle.getMessage(WizardInfoPanel.class, "WizardInfoPanel.jLabel2.text")); // NOI18N

        title.setText(org.openide.util.NbBundle.getMessage(WizardInfoPanel.class, "WizardInfoPanel.title.text")); // NOI18N
        title.setToolTipText(org.openide.util.NbBundle.getMessage(WizardInfoPanel.class, "WizardInfoPanel.title.toolTipText")); // NOI18N
        title.setName(org.openide.util.NbBundle.getMessage(WizardInfoPanel.class, "WizardInfoPanel.title.name")); // NOI18N

        jCheckBox1.setText(org.openide.util.NbBundle.getMessage(WizardInfoPanel.class, "WizardInfoPanel.jCheckBox1.text")); // NOI18N
        jCheckBox1.setToolTipText(org.openide.util.NbBundle.getMessage(WizardInfoPanel.class, "WizardInfoPanel.jCheckBox1.toolTipText")); // NOI18N
        jCheckBox1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBox1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox1.setName(org.openide.util.NbBundle.getMessage(WizardInfoPanel.class, "WizardInfoPanel.jCheckBox1.name")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE))
                    .addComponent(jCheckBox1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox1)
                .addContainerGap(166, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    public String validateContents(Component c, Object obj) {
        return title.getText().trim().length() == 0 ? "Enter a title" : null;
    }
    
    public static String getStep() {
        return "setTitle";
    }
    
    public static String getDescription() {
        return "Set Wizard Title";
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField title;
    // End of variables declaration//GEN-END:variables
    
}
