 
package loginWizardDemo;

import java.sql.Array;
import java.sql.Blob;
import java.sql.CallableStatement;
import java.sql.Clob;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.NClob;
import java.sql.PreparedStatement;
import java.sql.SQLClientInfoException;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.SQLXML;
import java.sql.Savepoint;
import java.sql.Statement;
import java.sql.Struct;
import java.util.Map;
import java.util.Properties;

/**
 * Fake connection used in this wizard demo for testing on systems without a datbase.
 * 
 * @author sknutson
 */
public class FakeConnection implements Connection
{

    public void clearWarnings() throws SQLException
    {
        throw new RuntimeException ("Fake driver for testing only");
        
    }

    public void close() throws SQLException
    {
        // no action on close, since we weren't really open        
    }

    public void commit() throws SQLException
    {
        throw new RuntimeException ("Fake driver for testing only");
        
    }

    public Statement createStatement() throws SQLException
    {
        throw new RuntimeException ("Fake driver for testing only");
        
    }

    public Statement createStatement(int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException
    {
        throw new RuntimeException ("Fake driver for testing only");
        
    }

    public Statement createStatement(int resultSetType, int resultSetConcurrency) throws SQLException
    {
        throw new RuntimeException ("Fake driver for testing only");
        
    }

    public boolean getAutoCommit() throws SQLException
    {
        throw new RuntimeException ("Fake driver for testing only");
    }

    public String getCatalog() throws SQLException
    {
        throw new RuntimeException ("Fake driver for testing only");
        
    }

    public int getHoldability() throws SQLException
    {
        throw new RuntimeException ("Fake driver for testing only");
    }

    public DatabaseMetaData getMetaData() throws SQLException
    {
        throw new RuntimeException ("Fake driver for testing only");
        
    }

    public int getTransactionIsolation() throws SQLException
    {
        throw new RuntimeException ("Fake driver for testing only");
    }

    public Map getTypeMap() throws SQLException
    {
        throw new RuntimeException ("Fake driver for testing only");
        
    }

    public SQLWarning getWarnings() throws SQLException
    {
        throw new RuntimeException ("Fake driver for testing only");
        
    }

    public boolean isClosed() throws SQLException
    {
        throw new RuntimeException ("Fake driver for testing only");
    }

    public boolean isReadOnly() throws SQLException
    {
        throw new RuntimeException ("Fake driver for testing only");
    }

    public String nativeSQL(String sql) throws SQLException
    {
        throw new RuntimeException ("Fake driver for testing only");
        
    }

    public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException
    {
        throw new RuntimeException ("Fake driver for testing only");
        
    }

    public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency) throws SQLException
    {
        throw new RuntimeException ("Fake driver for testing only");
        
    }

    public CallableStatement prepareCall(String sql) throws SQLException
    {
        throw new RuntimeException ("Fake driver for testing only");
        
    }

    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException
    {
        throw new RuntimeException ("Fake driver for testing only");
        
    }

    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency) throws SQLException
    {
        throw new RuntimeException ("Fake driver for testing only");
        
    }

    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException
    {
        throw new RuntimeException ("Fake driver for testing only");
        
    }

    public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException
    {
        throw new RuntimeException ("Fake driver for testing only");
        
    }

    public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException
    {
        throw new RuntimeException ("Fake driver for testing only");
        
    }

    public PreparedStatement prepareStatement(String sql) throws SQLException
    {
        throw new RuntimeException ("Fake driver for testing only");
        
    }

    public void releaseSavepoint(Savepoint savepoint) throws SQLException
    {
        throw new RuntimeException ("Fake driver for testing only");
        
    }

    public void rollback() throws SQLException
    {
        throw new RuntimeException ("Fake driver for testing only");
        
    }

    public void rollback(Savepoint savepoint) throws SQLException
    {
        throw new RuntimeException ("Fake driver for testing only");
        
    }

    public void setAutoCommit(boolean autoCommit) throws SQLException
    {
        throw new RuntimeException ("Fake driver for testing only");
        
    }

    public void setCatalog(String catalog) throws SQLException
    {
        throw new RuntimeException ("Fake driver for testing only");
        
    }

    public void setHoldability(int holdability) throws SQLException
    {
        throw new RuntimeException ("Fake driver for testing only");
        
    }

    public void setReadOnly(boolean readOnly) throws SQLException
    {
        throw new RuntimeException ("Fake driver for testing only");
        
    }

    public Savepoint setSavepoint() throws SQLException
    {
        throw new RuntimeException ("Fake driver for testing only");
        
    }

    public Savepoint setSavepoint(String name) throws SQLException
    {
        throw new RuntimeException ("Fake driver for testing only");
    }

    public void setTransactionIsolation(int level) throws SQLException
    {
        throw new RuntimeException ("Fake driver for testing only");
        
    }

    public void setTypeMap(Map map) throws SQLException
    {
        throw new RuntimeException ("Fake driver for testing only");
        
    }

    public Clob createClob() throws SQLException {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public Blob createBlob() throws SQLException {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public NClob createNClob() throws SQLException {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public SQLXML createSQLXML() throws SQLException {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public boolean isValid(int arg0) throws SQLException {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public void setClientInfo(String arg0, String arg1) throws SQLClientInfoException {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public void setClientInfo(Properties arg0) throws SQLClientInfoException {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public String getClientInfo(String arg0) throws SQLException {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public Properties getClientInfo() throws SQLException {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public Array createArrayOf(String arg0, Object[] arg1) throws SQLException {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public Struct createStruct(String arg0, Object[] arg1) throws SQLException {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public <T> T unwrap(Class<T> arg0) throws SQLException {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public boolean isWrapperFor(Class<?> arg0) throws SQLException {
        throw new UnsupportedOperationException("Not supported yet.");
    }

}

